// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardStats = `-- name: DashboardStats :one
SELECT
(
    SELECT COUNT(*) FROM users
) AS users,

(
    SELECT COUNT(*) FROM users
    WHERE role='admin'
) AS admins,

(
    SELECT COUNT(*) FROM users
    WHERE status='blocked'
) AS blocked_users,

(
    SELECT COUNT(*)
    FROM refresh_tokens
    WHERE revoked_at IS NULL
      AND expires_at > now()
) AS active_sessions
`

type DashboardStatsRow struct {
	Users          int64 `json:"users"`
	Admins         int64 `json:"admins"`
	BlockedUsers   int64 `json:"blocked_users"`
	ActiveSessions int64 `json:"active_sessions"`
}

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, dashboardStats)
	var i DashboardStatsRow
	err := row.Scan(
		&i.Users,
		&i.Admins,
		&i.BlockedUsers,
		&i.ActiveSessions,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET
    role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, status, created_at, updated_at, role
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET
    status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, status, created_at, updated_at, role
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
