// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    user_id,
    session_id,
    name,
    platform,
    fingerprint,
    vpn_uuid,
    last_ip
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, user_id, session_id, name, platform, fingerprint, vpn_uuid, last_ip, last_seen, created_at
`

type CreateDeviceParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	SessionID   pgtype.UUID `json:"session_id"`
	Name        string      `json:"name"`
	Platform    string      `json:"platform"`
	Fingerprint string      `json:"fingerprint"`
	VpnUuid     pgtype.UUID `json:"vpn_uuid"`
	LastIp      *netip.Addr `json:"last_ip"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.SessionID,
		arg.Name,
		arg.Platform,
		arg.Fingerprint,
		arg.VpnUuid,
		arg.LastIp,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Name,
		&i.Platform,
		&i.Fingerprint,
		&i.VpnUuid,
		&i.LastIp,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE
FROM devices
WHERE id=$1
`

func (q *Queries) DeleteDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const deleteUserDevices = `-- name: DeleteUserDevices :exec
DELETE
FROM devices
WHERE user_id=$1
`

func (q *Queries) DeleteUserDevices(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserDevices, userID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, session_id, name, platform, fingerprint, vpn_uuid, last_ip, last_seen, created_at
FROM devices
WHERE id=$1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Name,
		&i.Platform,
		&i.Fingerprint,
		&i.VpnUuid,
		&i.LastIp,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByFingerprint = `-- name: GetDeviceByFingerprint :one
SELECT id, user_id, session_id, name, platform, fingerprint, vpn_uuid, last_ip, last_seen, created_at
FROM devices
WHERE user_id = $1
  AND fingerprint = $2
`

type GetDeviceByFingerprintParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Fingerprint string      `json:"fingerprint"`
}

func (q *Queries) GetDeviceByFingerprint(ctx context.Context, arg GetDeviceByFingerprintParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByFingerprint, arg.UserID, arg.Fingerprint)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Name,
		&i.Platform,
		&i.Fingerprint,
		&i.VpnUuid,
		&i.LastIp,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceBySessionID = `-- name: GetDeviceBySessionID :one
SELECT id, user_id, session_id, name, platform, fingerprint, vpn_uuid, last_ip, last_seen, created_at
FROM devices
WHERE session_id = $1
`

func (q *Queries) GetDeviceBySessionID(ctx context.Context, sessionID pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceBySessionID, sessionID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Name,
		&i.Platform,
		&i.Fingerprint,
		&i.VpnUuid,
		&i.LastIp,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, session_id, name, platform, fingerprint, vpn_uuid, last_ip, last_seen, created_at
FROM devices
WHERE user_id=$1
ORDER BY last_seen DESC
`

func (q *Queries) ListDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Name,
			&i.Platform,
			&i.Fingerprint,
			&i.VpnUuid,
			&i.LastIp,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices
SET
    last_seen = now(),
    last_ip = $2
WHERE id = $1
`

type UpdateDeviceLastSeenParams struct {
	ID     pgtype.UUID `json:"id"`
	LastIp *netip.Addr `json:"last_ip"`
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, arg.ID, arg.LastIp)
	return err
}

const updateDeviceSession = `-- name: UpdateDeviceSession :exec
UPDATE devices
SET
    session_id = $2,
    last_seen = now(),
    last_ip = $3
WHERE id = $1
`

type UpdateDeviceSessionParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	LastIp    *netip.Addr `json:"last_ip"`
}

func (q *Queries) UpdateDeviceSession(ctx context.Context, arg UpdateDeviceSessionParams) error {
	_, err := q.db.Exec(ctx, updateDeviceSession, arg.ID, arg.SessionID, arg.LastIp)
	return err
}
