// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (
    project_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (project_id, user_id)
DO NOTHING
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    description,
    owner_id,
    visibility
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, owner_id, visibility, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Visibility  string      `json:"visibility"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_id, visibility, created_at, updated_at
FROM projects
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectRole = `-- name: GetProjectRole :one
SELECT role
FROM project_members
WHERE project_id = $1
AND user_id = $2
LIMIT 1
`

type GetProjectRoleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectRole(ctx context.Context, arg GetProjectRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.name, p.description, p.owner_id, p.visibility, p.created_at, p.updated_at
FROM projects p
JOIN project_members pm
    ON pm.project_id = p.id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExistsForUser = `-- name: ProjectExistsForUser :one
SELECT EXISTS(
    SELECT 1
    FROM project_members
    WHERE project_id = $1
    AND user_id = $2
)
`

type ProjectExistsForUserParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ProjectExistsForUser(ctx context.Context, arg ProjectExistsForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectExistsForUser, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE
FROM project_members
WHERE project_id = $1
AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = $2,
    description = $3,
    visibility = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, owner_id, visibility, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Visibility  string      `json:"visibility"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
