// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DashboardStats(ctx context.Context) (DashboardStatsRow, error)
	DeleteComment(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetComment(ctx context.Context, id pgtype.UUID) (Comment, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectRole(ctx context.Context, arg GetProjectRoleParams) (string, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListProjectsByUser(ctx context.Context, userID pgtype.UUID) ([]Project, error)
	ListTaskComments(ctx context.Context, taskID pgtype.UUID) ([]Comment, error)
	ListTasksByAssignee(ctx context.Context, assigneeID pgtype.UUID) ([]Task, error)
	ListTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]Task, error)
	ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error)
	ListUsers(ctx context.Context) ([]User, error)
	ProjectExistsForUser(ctx context.Context, arg ProjectExistsForUserParams) (bool, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
