// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    refresh_token_hash,
    device_name,
    ip,
    user_agent,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, refresh_token_hash, device_name, ip, user_agent, expires_at, last_seen, revoked, created_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	DeviceName       pgtype.Text        `json:"device_name"`
	Ip               *netip.Addr        `json:"ip"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceName,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE
FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token_hash, device_name, ip, user_agent, expires_at, last_seen, revoked, created_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, device_name, ip, user_agent, expires_at, last_seen, revoked, created_at
FROM sessions
WHERE refresh_token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, refresh_token_hash, device_name, ip, user_agent, expires_at, last_seen, revoked, created_at
FROM sessions
WHERE user_id = $1
AND revoked = false
ORDER BY last_seen DESC
`

func (q *Queries) ListSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceName,
			&i.Ip,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.LastSeen,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = true
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked = true
WHERE user_id = $1
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const updateSessionRefresh = `-- name: UpdateSessionRefresh :exec
UPDATE sessions
SET
    refresh_token_hash = $2,
    expires_at = $3,
    last_seen = now()
WHERE id = $1
`

type UpdateSessionRefreshParams struct {
	ID               pgtype.UUID        `json:"id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSessionRefresh(ctx context.Context, arg UpdateSessionRefreshParams) error {
	_, err := q.db.Exec(ctx, updateSessionRefresh, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}
