// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date,
    created_at,
    updated_at
`

type CreateTaskParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	CreatorID   pgtype.UUID        `json:"creator_id"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.CreatorID,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE
FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
    id,
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date,
    created_at,
    updated_at
FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT
    id,
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date,
    created_at,
    updated_at
FROM tasks
WHERE assignee_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByAssignee(ctx context.Context, assigneeID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee, assigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatorID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT
    id,
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date,
    created_at,
    updated_at
FROM tasks
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatorID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT
    id,
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date,
    created_at,
    updated_at
FROM tasks
WHERE project_id = $1
AND status = $2
ORDER BY created_at DESC
`

type ListTasksByStatusParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Status    string      `json:"status"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatorID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    assignee_id = $2,
    title = $3,
    description = $4,
    status = $5,
    priority = $6,
    due_date = $7,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    project_id,
    creator_id,
    assignee_id,
    title,
    description,
    status,
    priority,
    due_date,
    created_at,
    updated_at
`

type UpdateTaskParams struct {
	ID          pgtype.UUID        `json:"id"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatorID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
