// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpn.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVPNUser = `-- name: CreateVPNUser :one
INSERT INTO vpn_users (
    user_id,
    uuid,
    private_key,
    public_key,
    short_id,
    subscription_token
)
VALUES (
    $1,$2,$3,$4,$5,$6
)
RETURNING id, user_id, uuid, private_key, public_key, short_id, subscription_token, created_at
`

type CreateVPNUserParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	Uuid              string      `json:"uuid"`
	PrivateKey        string      `json:"private_key"`
	PublicKey         string      `json:"public_key"`
	ShortID           string      `json:"short_id"`
	SubscriptionToken string      `json:"subscription_token"`
}

func (q *Queries) CreateVPNUser(ctx context.Context, arg CreateVPNUserParams) (VpnUser, error) {
	row := q.db.QueryRow(ctx, createVPNUser,
		arg.UserID,
		arg.Uuid,
		arg.PrivateKey,
		arg.PublicKey,
		arg.ShortID,
		arg.SubscriptionToken,
	)
	var i VpnUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ShortID,
		&i.SubscriptionToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVPNConfig = `-- name: DeleteVPNConfig :exec

DELETE
FROM vpn_configs
WHERE id=$1
`

func (q *Queries) DeleteVPNConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVPNConfig, id)
	return err
}

const deleteVPNConfigsByDevice = `-- name: DeleteVPNConfigsByDevice :exec
DELETE
FROM vpn_configs
WHERE device_id = $1
`

func (q *Queries) DeleteVPNConfigsByDevice(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVPNConfigsByDevice, deviceID)
	return err
}

const deleteVPNConfigsByUser = `-- name: DeleteVPNConfigsByUser :exec
DELETE
FROM vpn_configs
WHERE vpn_user_id = $1
`

func (q *Queries) DeleteVPNConfigsByUser(ctx context.Context, vpnUserID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVPNConfigsByUser, vpnUserID)
	return err
}

const deleteVPNUser = `-- name: DeleteVPNUser :exec
DELETE
FROM vpn_users
WHERE user_id = $1
`

func (q *Queries) DeleteVPNUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVPNUser, userID)
	return err
}

const getVPNConfig = `-- name: GetVPNConfig :one

SELECT id, vpn_user_id, protocol, config, created_at, device_id
FROM vpn_configs
WHERE id=$1
`

func (q *Queries) GetVPNConfig(ctx context.Context, id pgtype.UUID) (VpnConfig, error) {
	row := q.db.QueryRow(ctx, getVPNConfig, id)
	var i VpnConfig
	err := row.Scan(
		&i.ID,
		&i.VpnUserID,
		&i.Protocol,
		&i.Config,
		&i.CreatedAt,
		&i.DeviceID,
	)
	return i, err
}

const getVPNUserBySubscription = `-- name: GetVPNUserBySubscription :one
SELECT id, user_id, uuid, private_key, public_key, short_id, subscription_token, created_at
FROM vpn_users
WHERE subscription_token=$1
`

func (q *Queries) GetVPNUserBySubscription(ctx context.Context, subscriptionToken string) (VpnUser, error) {
	row := q.db.QueryRow(ctx, getVPNUserBySubscription, subscriptionToken)
	var i VpnUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ShortID,
		&i.SubscriptionToken,
		&i.CreatedAt,
	)
	return i, err
}

const getVPNUserByUserID = `-- name: GetVPNUserByUserID :one
SELECT id, user_id, uuid, private_key, public_key, short_id, subscription_token, created_at
FROM vpn_users
WHERE user_id=$1
`

func (q *Queries) GetVPNUserByUserID(ctx context.Context, userID pgtype.UUID) (VpnUser, error) {
	row := q.db.QueryRow(ctx, getVPNUserByUserID, userID)
	var i VpnUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.PrivateKey,
		&i.PublicKey,
		&i.ShortID,
		&i.SubscriptionToken,
		&i.CreatedAt,
	)
	return i, err
}

const listVPNConfigs = `-- name: ListVPNConfigs :many
SELECT id, vpn_user_id, protocol, config, created_at, device_id
FROM vpn_configs
WHERE vpn_user_id=$1
`

func (q *Queries) ListVPNConfigs(ctx context.Context, vpnUserID pgtype.UUID) ([]VpnConfig, error) {
	rows, err := q.db.Query(ctx, listVPNConfigs, vpnUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VpnConfig
	for rows.Next() {
		var i VpnConfig
		if err := rows.Scan(
			&i.ID,
			&i.VpnUserID,
			&i.Protocol,
			&i.Config,
			&i.CreatedAt,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVPNUsers = `-- name: ListVPNUsers :many
SELECT id, user_id, uuid, private_key, public_key, short_id, subscription_token, created_at
FROM vpn_users
`

func (q *Queries) ListVPNUsers(ctx context.Context) ([]VpnUser, error) {
	rows, err := q.db.Query(ctx, listVPNUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VpnUser
	for rows.Next() {
		var i VpnUser
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Uuid,
			&i.PrivateKey,
			&i.PublicKey,
			&i.ShortID,
			&i.SubscriptionToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveVPNConfig = `-- name: SaveVPNConfig :one
INSERT INTO vpn_configs(
    vpn_user_id,
    device_id,
    protocol,
    config
)
VALUES(
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT(vpn_user_id, device_id, protocol)
DO UPDATE
SET config = EXCLUDED.config
RETURNING id, vpn_user_id, device_id, protocol, config, created_at
`

type SaveVPNConfigParams struct {
	VpnUserID pgtype.UUID `json:"vpn_user_id"`
	DeviceID  pgtype.UUID `json:"device_id"`
	Protocol  string      `json:"protocol"`
	Config    string      `json:"config"`
}

type SaveVPNConfigRow struct {
	ID        pgtype.UUID        `json:"id"`
	VpnUserID pgtype.UUID        `json:"vpn_user_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	Protocol  string             `json:"protocol"`
	Config    string             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveVPNConfig(ctx context.Context, arg SaveVPNConfigParams) (SaveVPNConfigRow, error) {
	row := q.db.QueryRow(ctx, saveVPNConfig,
		arg.VpnUserID,
		arg.DeviceID,
		arg.Protocol,
		arg.Config,
	)
	var i SaveVPNConfigRow
	err := row.Scan(
		&i.ID,
		&i.VpnUserID,
		&i.DeviceID,
		&i.Protocol,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}
