// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpn_devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVPNDevice = `-- name: CreateVPNDevice :one

INSERT INTO vpn_devices(
    vpn_user_id,
    name,
    platform,
    device_token
)
VALUES(
    $1,$2,$3,$4
)
RETURNING id, vpn_user_id, name, platform, device_token, last_seen_at, revoked, created_at
`

type CreateVPNDeviceParams struct {
	VpnUserID   pgtype.UUID `json:"vpn_user_id"`
	Name        string      `json:"name"`
	Platform    string      `json:"platform"`
	DeviceToken string      `json:"device_token"`
}

func (q *Queries) CreateVPNDevice(ctx context.Context, arg CreateVPNDeviceParams) (VpnDevice, error) {
	row := q.db.QueryRow(ctx, createVPNDevice,
		arg.VpnUserID,
		arg.Name,
		arg.Platform,
		arg.DeviceToken,
	)
	var i VpnDevice
	err := row.Scan(
		&i.ID,
		&i.VpnUserID,
		&i.Name,
		&i.Platform,
		&i.DeviceToken,
		&i.LastSeenAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVPNDevice = `-- name: DeleteVPNDevice :exec

DELETE
FROM vpn_devices
WHERE id=$1
`

func (q *Queries) DeleteVPNDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVPNDevice, id)
	return err
}

const getVPNDevice = `-- name: GetVPNDevice :one
SELECT id, vpn_user_id, name, platform, device_token, last_seen_at, revoked, created_at
FROM vpn_devices
WHERE id=$1
`

func (q *Queries) GetVPNDevice(ctx context.Context, id pgtype.UUID) (VpnDevice, error) {
	row := q.db.QueryRow(ctx, getVPNDevice, id)
	var i VpnDevice
	err := row.Scan(
		&i.ID,
		&i.VpnUserID,
		&i.Name,
		&i.Platform,
		&i.DeviceToken,
		&i.LastSeenAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const listVPNDevices = `-- name: ListVPNDevices :many

SELECT id, vpn_user_id, name, platform, device_token, last_seen_at, revoked, created_at
FROM vpn_devices
WHERE vpn_user_id=$1
ORDER BY created_at DESC
`

func (q *Queries) ListVPNDevices(ctx context.Context, vpnUserID pgtype.UUID) ([]VpnDevice, error) {
	rows, err := q.db.Query(ctx, listVPNDevices, vpnUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VpnDevice
	for rows.Next() {
		var i VpnDevice
		if err := rows.Scan(
			&i.ID,
			&i.VpnUserID,
			&i.Name,
			&i.Platform,
			&i.DeviceToken,
			&i.LastSeenAt,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeVPNDevice = `-- name: RevokeVPNDevice :exec

UPDATE vpn_devices
SET revoked=true
WHERE id=$1
`

func (q *Queries) RevokeVPNDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeVPNDevice, id)
	return err
}
